# Use this action if you need a version of dylan-tool newer than the one in the
# most recent Open Dylan release.  Normally it shouldn't be necessary to use
# this action since the install-opendylan action installs dylan-tool in its own
# bin directory.

name: install-dylan-tool
description: Install the dylan command-line tool
inputs:
  tag:
    required: false
    type: string
    default: v0.11.0

runs:
  using: composite
  steps:
    - uses: dylan-lang/install-opendylan@v3

    - uses: actions/checkout@v4
      with:
        repository: dylan-lang/dylan-tool
        submodules: recursive
        ref: ${{ inputs.tag }}
        path: dylan-tool

    - name: Build and install dylan-tool
      shell: bash
      run: |
        DYLAN=${GITHUB_WORKSPACE}/dylan-tool make -C dylan-tool install
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
        echo "${GITHUB_WORKSPACE}/dylan-tool/install/bin" >> ${GITHUB_PATH}
